"use client";

import { useEffect, useState } from "react";

/* Generated by LastMile without a model. The flows below come from the product
   spec; the screens are deliberately plain so the result is honest about how it
   was made. */

type Record = { id: string; title: string; notes: string; createdAt: string };

const KEY = "lastmile:want-you-create:scans";

export default function Page() {
  const [records, setRecords] = useState<Record[]>([]);
  const [title, setTitle] = useState("");
  const [notes, setNotes] = useState("");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(KEY);
      if (raw) setRecords(JSON.parse(raw) as Record[]);
    } catch {
      /* a corrupt value must not break the first render */
    }
    setReady(true);
  }, []);

  useEffect(() => {
    if (!ready) return;
    try {
      window.localStorage.setItem(KEY, JSON.stringify(records));
    } catch {
      /* storage full or blocked — the UI stays usable */
    }
  }, [records, ready]);

  function add(e: React.FormEvent) {
    e.preventDefault();
    const clean = title.trim();
    if (!clean) return;
    setRecords((r) => [
      { id: crypto.randomUUID(), title: clean, notes: notes.trim(), createdAt: new Date().toISOString() },
      ...r,
    ]);
    setTitle("");
    setNotes("");
  }

  function remove(id: string) {
    setRecords((r) => r.filter((x) => x.id !== id));
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-semibold tracking-tight">AdScope</h1>
      <p className="mt-2 text-sm opacity-70">An on-demand, side-panel ad inspector for Chrome that gives developers and ad-operations teams a transparent, real-time enumeration of every ad slot and network firing on the current page.</p>

      <form onSubmit={add} className="mt-8 space-y-3 rounded-lg border border-white/10 p-4">
        <label className="block text-xs uppercase tracking-widest opacity-60" htmlFor="title">
          Title
        </label>
        <input
          id="title"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          className="w-full rounded border border-white/15 bg-transparent px-3 py-2 text-sm outline-none focus:border-[var(--accent)]"
          placeholder="What needs recording?"
        />
        <textarea
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          rows={2}
          className="w-full resize-none rounded border border-white/15 bg-transparent px-3 py-2 text-sm outline-none focus:border-[var(--accent)]"
          placeholder="Notes (optional)"
        />
        <button
          type="submit"
          className="rounded bg-[var(--accent)] px-4 py-2 text-sm font-medium text-black disabled:opacity-40"
          disabled={title.trim().length === 0}
        >
          Add
        </button>
      </form>

      <section className="mt-8">
        <h2 className="text-xs uppercase tracking-widest opacity-60">
          {records.length === 0 ? "Nothing yet" : records.length + " saved"}
        </h2>

        {records.length === 0 ? (
          <p className="mt-3 rounded border border-dashed border-white/15 px-4 py-8 text-center text-sm opacity-70">
            Add the first one above — it is saved in this browser and survives a reload.
          </p>
        ) : (
          <ul className="mt-3 space-y-2">
            {records.map((r) => (
              <li key={r.id} className="flex items-start justify-between gap-4 rounded border border-white/10 px-4 py-3">
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium">{r.title}</p>
                  {r.notes ? <p className="mt-0.5 text-xs opacity-70">{r.notes}</p> : null}
                </div>
                <button onClick={() => remove(r.id)} className="shrink-0 text-xs opacity-60 hover:opacity-100">
                  Remove
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>

      <footer className="mt-12 border-t border-white/10 pt-4 text-xs opacity-50">
        Flows: On-demand page scan · Ad details inspection · Scan history persistence
      </footer>
    </main>
  );
}
